spring:
  profiles: acc
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
weather-app:
  app-id: 34a755b5784921587b8e366c277fa385
  lang-feature:
    is-enabled: true
    units: metrics
    lang: de


---

spring:
  profiles: prod
weather-app:
  app-id: 34a755b5784921587b8e366c277fa385
  lang-feature:
    is-enabled: false
    units: metrics
    lang: de
